language: csharp
solution: m0ch.sln
script:
  - xbuild /p:Configuration=Release m0ch.sln
  - mono ./packages/xunit.runner.console.2.3.1/tools/xunit.console.clr4.exe ./m0chTests/bin/Release/m0chTests.dll
