language: csharp
solution: m0ch.sln
install:
  - sudo apt-get install nunit-console
  - nuget restore m0ch.sln
script:
  - xbuild /p:Configuration=Release m0ch.sln
  - nunit-console ./m0chTests/bin/Release/m0chTests.dll