language: csharp
solution: m0ch.sln
install:
  - nuget restore m0ch.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - mono /p:Configuration=Release m0ch.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./m0chTests/bin/Release/m0chTests.dll
