language: csharp
solution: m0ch.sln
install:
  - nuget restore m0ch.sln
  - nuget install xunit.runners -Version 2.3.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release m0ch.sln
  - mono ./testrunner/xunit.runners.2.3.1/tools/xunit.console.clr4.exe ./m0chTests/bin/Release/m0chTests.dll
